/**
 * Los puzzles de la casa. Cuentas de 4.º de primaria (tablas, repartos,
 * dobles y mitades) y alguna pregunta de la historia. Cada paso trae su pista
 * y las «clues» aparecen si Paula oyó o leyó algo que ayuda.
 */
import type { Paint, PuzzleDef } from "../core/puzzle";

/** Los botes del estudio del pintor: rojo, amarillo, azul y blanco. */
const PAINTS: Paint[] = [
  { name: "rojo", color: 0xd8423a },
  { name: "amarillo", color: 0xf2c230 },
  { name: "azul", color: 0x2f63c8 },
  { name: "blanco", color: 0xf4efe6 },
];

const list: PuzzleDef[] = [
  {
    id: "reloj",
    title: "El reloj de las horas devoradas",
    story: "El reloj aritmético no da la hora: cuenta las noches que la casa fingió no oír a Inés. Tres discos, tres cuentas.",
    steps: [
      { kind: "number", prompt: "Siete noches sonaron nueve campanadas cada noche. ¿Cuántas campanadas en total?", answer: 63,
        hint: "Son 7 grupos de 9: 7 × 9. Si no te sale, suma 9 siete veces." },
      { kind: "number", prompt: "144 minutos se reparten entre las 12 marcas del reloj. ¿Cuántos minutos para cada marca?", answer: 12,
        hint: "Reparto en partes iguales: 144 ÷ 12. ¿Qué número por 12 da 144?" },
      { kind: "number", prompt: "Multiplica 18 por 4 y divide el resultado entre 6.", answer: 12,
        hint: "Por pasos: 18 × 4 = 72. Ahora 72 ÷ 6." },
    ],
    clues: [
      { if: { has: "pagina-elvira" }, text: "En la página de Elvira hay algo subrayado dos veces: 7 × 9." },
      { if: { flag: "pista-reloj" }, text: "Elvira y Nicanor lo dijeron: un error no rompe nada, el disco solo se para." },
    ],
    reward: [{ give: "engranaje-marfil" }, { complete: "reloj" }, { affinity: ["elvira", 5] }],
  },
  {
    id: "caldera",
    title: "La presión justa",
    story: "La caldera respira mal y el portón de abajo sigue atrancado. Los manómetros esperan una cifra exacta.",
    steps: [
      { kind: "number", prompt: "La tubería recibe 96 pulsos y los reparte entre 8 tubos. ¿Cuántos pulsos van por cada tubo?", answer: 12,
        hint: "96 ÷ 8. Piensa en la tabla del 8: ¿8 por cuánto da 96?" },
      { kind: "number", prompt: "Cada tubo gira siete veces más fuerte. ¿Qué presión marca el manómetro?", answer: 84,
        hint: "Los 12 pulsos de cada tubo, siete veces: 12 × 7." },
    ],
    clues: [
      { if: { chose: ["tomas", "caldera"] }, text: "Tomás: «Los pulsos se reparten entre los tubos, y cada salida gira siete veces»." },
      { if: { flag: "sabe-porton-presion" }, text: "Remedios y Tomás lo dijeron: con la presión justa, el portón cede." },
    ],
    reward: [{ set: "porton-abierto" }, { complete: "porton" }, { affinity: ["tomas", 6] }],
  },
  {
    id: "pacto",
    title: "El pacto de las trece campanadas",
    story: "El sello y el engranaje encajan en el altar. Para romper el pacto hay que decir en voz alta la cuenta completa.",
    steps: [
      { kind: "number", prompt: "Doce criados dejaron 5 velas cada uno en el altar. ¿Cuántas velas había?", answer: 60,
        hint: "12 grupos de 5: 12 × 5. Truco: 10 × 5 más 2 × 5." },
      { kind: "number", prompt: "La casa guardó 45 recuerdos en 3 cajones iguales. ¿Cuántos recuerdos hay en cada cajón?", answer: 15,
        hint: "45 ÷ 3. ¿Qué número sumado tres veces da 45?" },
      { kind: "choice", prompt: "¿Cuántas personas entraron en la capilla aquella noche?", options: ["Doce", "Trece", "Catorce"], answer: 1,
        hint: "Tomás lo contó: entraron los doce criados… y alguien más, escondido." },
    ],
    clues: [
      { if: { chose: ["tomas", "capilla"] }, text: "Tomás: «Trece criados entraron a rezar por Inés. Salieron doce»." },
      { if: { examined: "registro" }, text: "En el registro cosido había trece nombres; el último, tachado." },
    ],
    reward: [{ take: "engranaje-marfil" }, { take: "sello-aurelia" }, { set: "pacto-roto" }],
  },
  {
    id: "compuertas",
    title: "El camino del agua",
    story: "Tres compuertas dejan pasar el agua del aljibe. Si se abren en su orden, el túnel de la torre queda seco. Sin prisa: el agua avisa.",
    steps: [
      { kind: "number", prompt: "Tres canales llevan 48 litros cada uno. ¿Cuántos litros en total?", answer: 144,
        hint: "48 × 3. Por partes: 40 × 3 = 120 y 8 × 3 = 24." },
      { kind: "number", prompt: "Esos 144 litros se reparten entre 8 desagües. ¿Cuántos litros por desagüe?", answer: 18,
        hint: "144 ÷ 8. La mitad de 144 es 72, la mitad de 72 es 36… y otra mitad más." },
      { kind: "choice", prompt: "La I se abre antes que la III. La II, después de la III. ¿Qué orden es el bueno?",
        options: ["I · II · III", "I · III · II", "III · I · II"], answer: 1,
        hint: "Pon primero la I. Luego la III. La II va la última." },
    ],
    clues: [{ if: { flag: "pista-compuertas" }, text: "Tadeo y Anselmo lo dijeron: «la primera antes que la tercera; la segunda, después»." }],
    reward: [{ set: "compuertas-abiertas" }],
  },
  {
    id: "estrellas",
    title: "El cerrojo de estrellas",
    story: "Con la lente de luna, el telescopio muestra el cerrojo de la pasarela: una rueda de constelaciones.",
    steps: [
      { kind: "number", prompt: "El cielo tiene 360 grados y 12 constelaciones iguales. ¿Cuántos grados ocupa cada una?", answer: 30,
        hint: "360 ÷ 12. Piensa: 12 × 3 = 36, así que 12 × 30 = 360." },
      { kind: "number", prompt: "Nueve planetas dan 7 vueltas cada uno. ¿Cuántas vueltas en total?", answer: 63,
        hint: "9 × 7, que es lo mismo que 7 × 9." },
    ],
    clues: [{ if: { examined: "cuaderno-estrellas" }, text: "En el cuaderno de Inés: «el cielo se reparte en doce casas iguales»." }],
    reward: [{ set: "pasarela-abierta" }],
  },
  {
    id: "caja",
    title: "La caja de música de Inés",
    story: "El cilindro repite un patrón. Si se completa, la caja se abre.",
    steps: [
      { kind: "number", prompt: "La cajita toca cada vez el doble: 3, 6, 12, 24… ¿Qué número sigue?", answer: 48,
        hint: "Cada número es el doble del anterior. ¿Cuánto es 24 + 24?" },
      { kind: "number", prompt: "La melodía tiene 96 notas en 8 compases iguales. ¿Cuántas notas hay en cada compás?", answer: 12,
        hint: "96 ÷ 8. ¿8 por cuánto da 96?" },
    ],
    reward: [{ give: "canica-azul" }, { count: "recuerdos" }],
  },
  {
    id: "retratos",
    title: "La familia que cambió de sitio",
    story: "Los retratos se descolocaron solos. Si vuelven a su sitio, el marco de Inés se abre.",
    steps: [
      { kind: "choice", prompt: "Aurelia está a la izquierda de Tomás. Elvira, a la derecha de Tomás. ¿Quién va en el centro?",
        options: ["Aurelia", "Tomás", "Elvira"], answer: 1, hint: "No hace falta contar: imagina tres cuadros en fila." },
      { kind: "number", prompt: "6 retratos esconden 4 símbolos cada uno. ¿Cuántos símbolos hay en total?", answer: 24,
        hint: "6 × 4. O suma 4 seis veces." },
    ],
    reward: [{ give: "foto-ines" }, { count: "recuerdos" }],
  },
  {
    id: "melodia",
    title: "La melodía de los nombres",
    story: "El gramófono guarda un cilindro de cera, pero solo lo suelta si suena la melodía de la casa.",
    steps: [
      { kind: "choice", prompt: "DO, MI, SOL, DO, MI, SOL… ¿Qué nota sigue?", options: ["DO", "RE", "MI", "FA", "SOL", "LA"], answer: 0,
        hint: "El patrón se repite igual. ¿Qué nota va justo después de SOL la primera vez?" },
      { kind: "number", prompt: "El gramófono da 18 vueltas por minuto durante 4 minutos. ¿Cuántas vueltas da?", answer: 72,
        hint: "18 × 4. Por partes: 10 × 4 = 40 y 8 × 4 = 32." },
      { kind: "number", prompt: "Reparte esas 72 vueltas entre 6 pistas. ¿Cuántas por pista?", answer: 12,
        hint: "72 ÷ 6. ¿6 por cuánto da 72?" },
    ],
    clues: [
      { if: { flag: "sabe-melodia" }, text: "Baltasar: «¡Después del sol, vuelta a empezar! Do»." },
      { if: { flag: "pista-melodia" }, text: "Baltasar y Críspulo lo dijeron: tres notas y vuelta a empezar." },
    ],
    reward: [{ give: "cilindro-cera" }, { count: "recuerdos" }],
  },
  {
    id: "antidoto",
    title: "El antídoto de luna",
    story: "La señora Bruma necesita las proporciones exactas para que las flores dejen de repetir voces ajenas.",
    steps: [
      { kind: "number", prompt: "Hay 8 macetas con 3 flores de luna cada una. ¿Cuántas flores hay?", answer: 24,
        hint: "8 macetas de 3 flores: 8 × 3." },
      { kind: "number", prompt: "Reparte 72 gotas de rocío entre 9 raíces. ¿Cuántas gotas le tocan a cada raíz?", answer: 8,
        hint: "72 ÷ 9. ¿9 por cuánto da 72?" },
      { kind: "number", prompt: "Cada uno de 7 frascos lleva 6 hojas, y la mitad se tira. ¿Cuántas hojas quedan?", answer: 21,
        hint: "Primero 6 × 7 = 42. Luego la mitad de 42." },
    ],
    clues: [{ if: { chose: ["bruma", "flores"] }, text: "Bruma: «Ocho macetas, tres flores en cada una»." }],
    reward: [{ give: "flor-luna" }, { give: "lente-luna" }, { count: "recuerdos" }, { complete: "antidoto" }, { affinity: ["bruma", 6] }],
  },
  {
    id: "baules",
    title: "Los baúles sin dueño",
    story: "Gafe puede colarse entre los baúles, pero Paula tiene que decirle cuál es.",
    steps: [
      { kind: "number", prompt: "Hay 5 filas de 9 baúles. ¿Cuántos baúles hay?", answer: 45, hint: "5 × 9." },
      { kind: "number", prompt: "Gafe ya ha olfateado la tercera parte. ¿Cuántos baúles ha olfateado?", answer: 15,
        hint: "La tercera parte de 45 es 45 ÷ 3." },
      { kind: "number", prompt: "El baúl bueno lleva el doble de 14, dividido entre 4. ¿Qué número tiene?", answer: 7,
        hint: "El doble de 14 es 28. Ahora 28 ÷ 4." },
    ],
    clues: [{ if: { flag: "pista-baul" }, text: "Pepito lo contó: el baúl bueno tiene un siete pintado y huele a tinta." }],
    reward: [{ give: "plano-ines" }],
  },
  {
    id: "campana",
    title: "La decimotercera campanada",
    story: "No hay que golpear la campana: hay que contarle la cuenta entera, y ella sonará sola por Inés.",
    steps: [
      { kind: "number", prompt: "Cada uno de los 5 recuerdos guarda 13 ecos. ¿Cuántos ecos llevas?", answer: 65,
        hint: "13 × 5. Por partes: 10 × 5 = 50 y 3 × 5 = 15." },
      { kind: "number", prompt: "Aurelia dejó 7 llaves a cada una de 12 personas. Inés devolvió la mitad. ¿Cuántas llaves quedaron?", answer: 42,
        hint: "Primero 7 × 12 = 84. Quedó la mitad." },
      { kind: "choice", prompt: "¿Quién ha acompañado a Paula incluso cuando la casa mentía?", options: ["Don Basilio", "Gafe", "Elvira", "Tomás"], answer: 1,
        hint: "Tiene cuatro patas y los ojos de color ámbar." },
    ],
    clues: [
      { if: { flag: "pista-campana" }, text: "Pepito te lo susurró: «la campana no se golpea; se le cuenta la verdad»." },
      { if: { chose: ["florentina", "cinta"] }, text: "Florentina: «la respuesta no necesita golpes»." },
    ],
    reward: [{ set: "final" }, { complete: "trece" }, { complete: "recuerdos" }, { complete: "fiesta" }],
  },

  // ======================================================== ala de la fiesta
  {
    id: "vals",
    title: "El vals que nadie bailó",
    story: "La orquesta fantasma olvidó el vals de la fiesta de Inés. El maestro Anacleto lo tararea a trozos: escúchalo y tócalo igual en el piano de la tarima.",
    steps: [
      { kind: "melody", prompt: "Escucha el principio del vals y tócalo igual.", notes: [0, 2, 4],
        hint: "Son tres notas que suben: do, mi, sol. ¡Las mismas de la caja de música!" },
      { kind: "melody", prompt: "Ahora la segunda parte: escucha bien y repítela.", notes: [4, 2, 0, 2],
        hint: "Baja y vuelve a subir: sol, mi, do… y otra vez mi." },
      { kind: "melody", prompt: "¡El final! Es un poco más largo.", notes: [0, 2, 4, 5, 4],
        hint: "Sube como al principio (do, mi, sol), da un saltito a la y vuelve a sol." },
    ],
    clues: [
      { if: { flag: "sabe-melodia" }, text: "Baltasar: «Do, mi, sol… y otra vez do»." },
      { if: { chose: ["anacleto", "vals"] }, text: "Anacleto: «Empieza como la caja de música de Inés»." },
      { if: { flag: "pista-vals" }, text: "Anacleto y Críspulo: «do, mi, sol… y luego baja como la lluvia: sol, mi, do»." },
    ],
    reward: [{ give: "partitura-vals" }, { count: "fiesta" }, { affinity: ["anacleto", 6] }],
  },
  {
    id: "banquete",
    title: "La mesa de los invitados",
    story: "Tía Clemencia quiere la mesa perfecta para la fiesta: la tarta partida en trozos iguales y cada plato en su sitio.",
    steps: [
      { kind: "number", prompt: "La tarta tiene 3 pisos y cada piso se corta en 8 trozos. ¿Cuántos trozos hay?", answer: 24,
        hint: "3 pisos de 8 trozos: 3 × 8. O suma 8 + 8 + 8." },
      { kind: "number", prompt: "Esos 24 trozos se reparten entre los 12 criados de la casa. ¿Cuántos trozos le tocan a cada uno?", answer: 2,
        hint: "24 ÷ 12. ¿Qué número por 12 da 24?" },
      { kind: "order", prompt: "Coloca la vajilla de la más grande a la más pequeña.",
        items: ["🍲 Sopera", "🍽️ Plato llano", "🥣 Plato hondo", "🍰 Plato de postre", "☕ Platito del té"],
        hint: "Empieza por la sopera, que es enorme, y acaba por el platito del té, que es el más pequeño." },
    ],
    clues: [
      { if: { chose: ["clemencia", "tarta"] }, text: "Tía Clemencia: «Tres pisos, ocho trozos por piso. Y que nadie se quede sin tarta»." },
      { if: { flag: "pista-tarta" }, text: "Remedios: «Salen a dos trozos por cabeza»." },
    ],
    reward: [{ give: "tarta-ines" }, { count: "fiesta" }, { affinity: ["clemencia", 6] }],
  },
  {
    id: "laberinto",
    title: "El laberinto de las luciérnagas",
    story: "Las luciérnagas de la fiesta se han perdido entre los setos. Lleva la lucecita hasta el farolillo: donde llega una, la siguen las demás.",
    steps: [
      { kind: "maze", prompt: "Lleva la luciérnaga hasta el farolillo 🏮 con las flechas (o tocando la casilla de al lado).",
        grid: ["S..#...", "##.#.#.", "...#.#.", ".###.#.", ".....#E"],
        hint: "Baja por la izquierda del todo, cruza por abajo y sube por la columna del medio hasta arriba." },
      { kind: "maze", prompt: "¡Muy bien! Este laberinto es más grande. Sin prisa.",
        grid: ["S.....#....", "#####.#.##.", "....#...#..", ".##.####.#.", ".#......#..", ".#.####.##.", "...#......E"],
        hint: "Sigue la fila de arriba hacia la derecha y baja por el primer hueco entre los setos." },
    ],
    clues: [{ if: { chose: ["ramona", "laberinto"] }, text: "Ramona la lechuza: «Desde arriba se ve: la luz siempre quiere ir hacia la derecha»." }],
    reward: [{ give: "farolillos" }, { count: "fiesta" }, { affinity: ["ramona", 5] }],
  },
  {
    id: "automata",
    title: "La bailarina dormida",
    story: "Casimiro terminó la bailarina de cuerda para el cumpleaños de Inés, pero las piezas se le mezclaron en el cajón.",
    steps: [
      { kind: "pairs", prompt: "Encuentra las parejas de piezas iguales. Da la vuelta a dos cartas cada vez.",
        icons: ["⚙️", "🔩", "🎀", "🥁", "🐴", "🎩"],
        hint: "Fíjate bien en cada carta que levantes: si luego sale su pareja, ya sabrás dónde estaba." },
      { kind: "choice", prompt: "La rueda grande gira hacia la derecha. La rueda pequeña está enganchada a ella. ¿Hacia dónde gira la pequeña?",
        options: ["Hacia la derecha", "Hacia la izquierda", "No se mueve"], answer: 1,
        hint: "Dos ruedas dentadas que se tocan giran al revés una de otra. Pruébalo con los dos dedos índices." },
      { kind: "number", prompt: "Con cada vuelta de llave, la bailarina da 4 vueltas. Si le das 6 vueltas a la llave, ¿cuántas vueltas baila?", answer: 24,
        hint: "6 vueltas de llave y 4 vueltas de baile por cada una: 6 × 4." },
    ],
    clues: [{ if: { chose: ["casimiro", "ruedas"] }, text: "Casimiro: «Las ruedas que se besan giran al revés»." }],
    reward: [{ give: "bailarina-cuerda" }, { count: "fiesta" }, { affinity: ["casimiro", 6] }],
  },
  {
    id: "colores",
    title: "Los colores de la fiesta",
    story: "Don Fermín pinta las invitaciones de la fiesta, pero solo le quedan tres botes de colores y uno de blanco. Los demás colores hay que mezclarlos.",
    steps: [
      { kind: "mix", prompt: "Haz el naranja para las invitaciones de las calabazas.",
        target: { name: "naranja", color: 0xef8a2e }, paints: PAINTS, answer: [0, 1],
        hint: "El naranja sale de mezclar el rojo con el amarillo." },
      { kind: "mix", prompt: "Ahora el verde de los setos del jardín.",
        target: { name: "verde", color: 0x4f9e4a }, paints: PAINTS, answer: [1, 2],
        hint: "Amarillo y azul juntos hacen verde." },
      { kind: "mix", prompt: "El morado de las ciruelas de la tarta.",
        target: { name: "morado", color: 0x7c4aa6 }, paints: PAINTS, answer: [0, 2],
        hint: "Rojo y azul: ¡morado!" },
      { kind: "mix", prompt: "Y el rosa del lazo de Inés.",
        target: { name: "rosa", color: 0xf09ab0 }, paints: PAINTS, answer: [0, 3],
        hint: "El rosa es rojo con mucho blanco." },
    ],
    clues: [
      { if: { chose: ["fermin", "colores"] }, text: "Don Fermín: «Con rojo, amarillo, azul y blanco se pinta el mundo entero»." },
      { if: { flag: "pista-colores" }, text: "Clotilde: «Rojo y blanco dan el rosa del lazo de Inés»." },
    ],
    reward: [{ give: "invitaciones" }, { count: "fiesta" }, { affinity: ["fermin", 6] }],
  },
  {
    id: "funcion",
    title: "La función de marionetas",
    story: "Bartolo preparó para Inés la función «La niña que contó hasta trece», pero las escenas y las marionetas se han desordenado.",
    steps: [
      { kind: "order", prompt: "Ordena las escenas de la función, de la primera a la última.",
        items: ["🌧️ Una noche de tormenta, una niña llega a la casa", "🔔 La casa cuenta hasta trece y todos se olvidan", "🐈‍⬛ Un gato negro encuentra los recuerdos", "🎉 La casa celebra la fiesta y amanece"],
        hint: "Toda historia empieza con alguien que llega y acaba con una fiesta. En medio, primero el problema y luego quien lo arregla." },
      { kind: "order", prompt: "Cuelga las marionetas de la más bajita a la más alta.",
        items: ["🐭 Ratón (10 cm)", "🐈‍⬛ Gato (25 cm)", "👸 Princesa (40 cm)", "🐉 Dragón (60 cm)"],
        hint: "Mira los centímetros: primero el número más pequeño." },
      { kind: "choice", prompt: "La adivinanza del final: «Tiene dientes y no muerde, abre puertas y no es persona». ¿Qué es?",
        options: ["Un peine", "Una llave", "Un gato"], answer: 1,
        hint: "Leocadia lleva un manojo colgado del cinturón y hace clin, clin." },
    ],
    clues: [{ if: { chose: ["bartolo", "funcion"] }, text: "Bartolo: «Primero llega la niña, luego la casa se olvida, luego el gato… y al final, ¡fiesta!»." }],
    reward: [{ give: "marioneta-ines" }, { count: "fiesta" }, { affinity: ["bartolo", 6] }],
  },
];

export const PUZZLES: Record<string, PuzzleDef> = Object.fromEntries(list.map((p) => [p.id, p]));
